### ISSUE TITLE
cannot work with mode-watcher

### ISSUE THREAD

**Issue by leonwang908** [BearToCode/carta#57]
carta will stop rendering stuff like highlightjs, `<h1>` if I do like below in +layout.svelte

```js
import { ModeWatcher, setMode, resetMode } from 'mode-watcher';
```

btw, is there any easy way to add dual theme like light/dark in carta?

**Comment by BearToCode** [comment]
Hello,

I updated docs to include a simple explanation to implement a dark mode, you can check them out [here](https://beartocode.github.io/carta/editing-styles#dark-mode), but all you have to do is the following:

```css
/* Editor dark mode */
/* Only if you are using the default theme */
html.dark .carta-theme__default {
	--border-color: var(--border-color-dark);
	--selection-color: var(--selection-color-dark);
	--focus-outline: var(--focus-outline-dark);
	--hover-color: var(--hover-color-dark);
	--caret-color: var(--caret-color-dark);
	--text-color: var(--text-color-dark);
}

/* Code dark mode */
/* Only if you didn't specify a custom code theme */
html.dark .shiki,
html.dark .shiki span {
	color: var(--shiki-dark) !important;
}
```

I do not how mode-watcher works, but if it just sets a `class="dark"` to the root `html` element(or `body`...), it should work fine with the instructions explained above.

Let me know if this solved your issue.
