### ISSUE TITLE
[plugin-emoji] default css is a little wonky

### ISSUE THREAD

**Issue by warren-bank** [BearToCode/carta#90]
I adjusted my own instance with:

```js
  import '@cartamd/plugin-emoji/default.css'
  import './css/emoji.css'
```

where _emoji.css_ includes the following overrides:

```css
.carta-emoji {
  display: block !important;
  word-break: break-word !important;
  overflow-x: auto;
  overflow-y: auto !important;
}

.carta-emoji button {
  display: inline-block !important;
  margin: 3px;
  height: 2rem;
  aspect-ratio: unset !important;
  white-space: nowrap;
}
```

to summarize:
* the main issue is that several emoji codes each resolve to a sequence of unicode characters
* the [default css](https://github.com/BearToCode/carta/blob/%40cartamd/plugin-emoji-v4.0.3/packages/plugin-emoji/src/lib/default.css) uses a grid layout, so an extra wide button stretches the width of an entire column
* the [default css](https://github.com/BearToCode/carta/blob/%40cartamd/plugin-emoji-v4.0.3/packages/plugin-emoji/src/lib/default.css) uses an aspect ratio of 1, so an extra wide button is also made extra tall.. and stretches the height of an entire row

test case:
1. type: `:h`
2. type: `:he`
3. type: `:hea`
   - several of the _heart_ emojis are multi character
